version: '3.9'

services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres-14
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_URL}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USERNAME=${DB_USER}
    env_file:
      - .env