version: '3.9'

services:

  postgres:
    image: postgis/postgis:14-3.5-alpine
    container_name: eventhub_postgres
    hostname: eventhub_postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_URL}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USERNAME=${DB_USER}
    env_file:
      - .env
    networks:
      eventhub_network:

  backend:
    image: openjdk:21
    container_name: eventhub_backend
    ports:
      - "9500:9500"
    volumes:
      - ./target/eventhub-0.0.1-SNAPSHOT.jar:/opt/app.jar
    command: java -jar -Ddb.url=jdbc:postgresql://eventhub_postgres:5432/${DB_NAME} /opt/app.jar
    networks:
      eventhub_network:
    env_file:
      - .env

networks:
  eventhub_network:
    name: 'eventhub_network'