spring:
  application:
    name: eventhub
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db.url:jdbc:postgresql://localhost:5432/postgres}
    username: ${db.username:postgres}
    password: ${db.password:postgres}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 9500
  servlet:
    context-path: /api

jwt:
  secret: "MySuperLongSecretKeyThatIsAtLeast32CharsMySuperLongSecretKeyThatIsAtLeast32Chars"